import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import auth from './routes/auth.js';
import crud from './routes/crud.js';
import analytics from './routes/analytics.js';
import { errorHandler, notFound } from './middleware/errors.js';

const app = express();
app.use(helmet());
app.use(cors({ origin: env.CLIENT_URL }));
app.use(express.json({ limit: '1mb' }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-7' }));
app.get('/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api/auth', auth);
app.use('/api', crud);
app.use('/api/analytics', analytics);
app.use(notFound);
app.use(errorHandler);
app.listen(env.PORT, () => console.log(`NexusOps API listening on port ${env.PORT}`));
