import { CalendarDays, ChevronDown, Download, TrendingUp } from 'lucide-react'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { RevenueChart, GrowthChart } from '../components/Charts'
import { Icon } from '../components/Icons'
import { getAnalytics } from '../services/api'

export function Analytics() {
  const [days, setDays] = useState(30)
  const analytics = useQuery({ queryKey: ['analytics', days], queryFn: () => getAnalytics(days), retry: 1 })
  const data = analytics.data
  const revenueData = data?.revenueOverTime.map((item) => ({ month: new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }), revenue: Number((item.revenue / 1000).toFixed(1)), target: 0 })) ?? []
  const growthData = data?.customerGrowth.map((item) => ({ month: new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }), value: item.newCustomers })) ?? []
  const averageOrder = data?.orders ? data.revenue / data.orders : 0
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Insights</p><h1>Analytics</h1><p className="page-subtitle">Understand the signals behind your growth.</p></div><div className="heading-actions"><select className="button secondary" value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last year</option></select><button className="button secondary" onClick={() => window.print()}><Download size={16} /> Export</button></div></div>{analytics.isError && <div className="form-error" role="alert">Analytics data is unavailable. Start the API and try again.</div>}<div className="analytics-kpis">{[['Net revenue', data ? `$${data.revenue.toLocaleString('en-US', { maximumFractionDigits: 0 })}` : '—', 'Live', 'CircleDollarSign', 'coral'], ['Active customers', data?.customers.toLocaleString() ?? '—', 'Live', 'UsersRound', 'mint'], ['Avg. order value', data ? `$${averageOrder.toFixed(2)}` : '—', 'Live', 'ShoppingBag', 'blue'], ['Products', data?.products.toLocaleString() ?? '—', 'Live', 'Package', 'purple']].map(([label, value, change, icon, tone]) => <div className="stat-card analytics-stat" key={label}><div className={`stat-icon ${tone}`}><Icon name={icon} size={17} /></div><p className="stat-label">{label}</p><div className="stat-value">{analytics.isLoading ? '—' : value}</div><span className="change positive"><TrendingUp size={13} /> {change}</span></div>)}</div><div className="content-grid chart-grid"><section className="panel chart-panel"><div className="panel-header"><div><h2>Revenue analytics</h2><p className="panel-subtitle">Revenue across your business</p></div><span className="select-button">{days} days <ChevronDown size={14} /></span></div><RevenueChart data={revenueData} /></section><section className="panel chart-panel"><div className="panel-header"><div><h2>Customer analytics</h2><p className="panel-subtitle">New customer growth</p></div><span className="select-button">Live data <ChevronDown size={14} /></span></div><GrowthChart data={growthData} /></section></div><section className="panel sales-breakdown"><div className="panel-header"><div><h2>Sales by channel</h2><p className="panel-subtitle">Where your revenue is coming from</p></div></div>{[['Direct sales', '$48,294', '42%', 'coral'], ['Partner network', '$32,918', '29%', 'mint'], ['Self-serve', '$21,600', '19%', 'blue'], ['Marketplace', '$12,680', '10%', 'purple']].map(([label, amount, percent, tone]) => <div className="channel-row" key={label}><span className={`channel-dot ${tone}`} /><strong>{label}</strong><div className="channel-bar"><span className={tone} style={{ width: percent }} /></div><span className="muted-cell">{percent}</span><strong>{amount}</strong></div>)}</section></div>
}
