import { ArrowDownRight, ArrowUpRight, ChevronDown, Download, MoreHorizontal, Plus, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Badge } from '../components/Badge'
import { GrowthChart, RevenueChart } from '../components/Charts'
import { Icon } from '../components/Icons'
import { orders } from '../data'
import { getOverview } from '../services/api'

const stats = [{ label: 'Total revenue', value: '$48,294.00', change: '+12.5%', up: true, icon: 'CircleDollarSign', tone: 'coral' }, { label: 'Total customers', value: '2,842', change: '+8.2%', up: true, icon: 'UsersRound', tone: 'mint' }, { label: 'Total orders', value: '1,284', change: '+4.6%', up: true, icon: 'ShoppingBag', tone: 'blue' }, { label: 'Conversion rate', value: '4.32%', change: '-1.2%', up: false, icon: 'Percent', tone: 'purple' }]
export function Dashboard() {
  const overview = useQuery({ queryKey: ['overview'], queryFn: getOverview, retry: 1 })
  const liveStats = overview.data ? [
    { ...stats[0], value: `$${overview.data.revenue.toLocaleString('en-US', { minimumFractionDigits: 2 })}` },
    { ...stats[1], value: overview.data.customers.toLocaleString() },
    { ...stats[2], value: overview.data.orders.toLocaleString() },
    { ...stats[3], value: overview.data.customers ? `${((overview.data.orders / overview.data.customers) * 100).toFixed(2)}%` : '0.00%' },
  ] : stats
  return <div className="page">
    <div className="page-heading"><div><p className="eyebrow">Tuesday, October 22, 2024</p><h1>Good morning, Basel <span className="wave">👋</span></h1><p className="page-subtitle">Here’s what’s happening with your business today.</p></div><div className="heading-actions"><button className="button secondary"><Download size={16} /> Export</button><button className="button primary"><Plus size={16} /> Add new</button></div></div>
    {overview.isError && <div className="form-error" role="alert">Live dashboard data is unavailable. Start the API to see current metrics.</div>}
    <div className="stats-grid">{liveStats.map((stat) => <div className="stat-card" key={stat.label}><div className="stat-top"><span className={`stat-icon ${stat.tone}`}><Icon name={stat.icon} size={17} /></span><button className="ghost-icon" aria-label={`${stat.label} options`}><MoreHorizontal size={17} /></button></div><p className="stat-label">{stat.label}</p><div className="stat-value">{overview.isLoading ? '—' : stat.value}</div><div className="stat-footer"><span className={`change ${stat.up ? 'positive' : 'negative'}`}>{stat.up ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{stat.change}</span><span className="muted-small">vs last month</span></div></div>)}</div>
    <div className="content-grid chart-grid"><section className="panel chart-panel"><div className="panel-header"><div><h2>Revenue overview</h2><p className="panel-subtitle">Monthly revenue performance</p></div><div className="panel-actions"><button className="select-button">Last 6 months <ChevronDown size={14} /></button><button className="ghost-icon"><MoreHorizontal size={18} /></button></div></div><div className="chart-legend"><span><i className="legend-dot coral" /> Revenue</span><span><i className="legend-line" /> Target</span><span className="chart-total">$48.3k <span className="change positive">+12.5%</span></span></div><RevenueChart /></section><section className="panel chart-panel"><div className="panel-header"><div><h2>Customer growth</h2><p className="panel-subtitle">New customers over time</p></div><button className="ghost-icon"><MoreHorizontal size={18} /></button></div><div className="chart-legend"><span><i className="legend-dot mint" /> Customers</span><span className="chart-total">2,842 <span className="change positive">+8.2%</span></span></div><GrowthChart /></section></div>
    <div className="content-grid bottom-grid"><section className="panel"><div className="panel-header"><div><h2>Recent transactions</h2><p className="panel-subtitle">Your latest orders and payments</p></div><Link className="text-link" to="/orders">View all <ArrowUpRight size={14} /></Link></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.slice(0, 4).map((order) => <tr key={order.id}><td><div className="person"><div className={`avatar ${order.color}`}>{order.initials}</div><div><strong>{order.customer}</strong><small>{order.email}</small></div></div></td><td className="muted-cell">{order.date}</td><td><strong>{order.amount}</strong></td><td><Badge status={order.status} /></td></tr>)}</tbody></table></div></section><section className="panel activity-panel"><div className="panel-header"><div><h2>Recent activity</h2><p className="panel-subtitle">Latest team updates</p></div><button className="ghost-icon"><MoreHorizontal size={18} /></button></div><div className="activity-list"><div className="activity"><div className="activity-icon coral-bg"><Icon name="CreditCard" size={15} /></div><div><p><strong>Olivia Rhye</strong> completed a payment</p><small>2 minutes ago · $1,240.00</small></div></div><div className="activity"><div className="activity-icon mint-bg"><Icon name="UserPlus" size={15} /></div><div><p><strong>New customer</strong> joined the workspace</p><small>24 minutes ago · Phoenix Baker</small></div></div><div className="activity"><div className="activity-icon blue-bg"><Icon name="FileCheck2" size={15} /></div><div><p><strong>Monthly report</strong> was generated</p><small>1 hour ago · October 2024</small></div></div><div className="activity"><div className="activity-icon purple-bg"><Icon name="MessageSquare" size={15} /></div><div><p><strong>Support ticket</strong> received a reply</p><small>3 hours ago · #TKT-2381</small></div></div></div></section></div>
    <div className="content-grid bottom-grid"><section className="panel products-panel"><div className="panel-header"><div><h2>Top products</h2><p className="panel-subtitle">Best performing this month</p></div><button className="ghost-icon"><MoreHorizontal size={18} /></button></div>{[['Analytics Pro', '$18,420', '38%', 'coral'], ['Team workspace', '$12,890', '27%', 'mint'], ['Automations', '$9,460', '21%', 'blue']].map(([name, amount, percent, tone]) => <div className="product-row" key={name}><div className={`product-icon ${tone}`}><Icon name={name === 'Analytics Pro' ? 'BarChart3' : name === 'Team workspace' ? 'UsersRound' : 'Zap'} size={17} /></div><div className="product-name"><strong>{name}</strong><div className="progress"><span className={tone} style={{ width: percent }} /></div></div><strong>{amount}</strong><span className="percent">{percent}</span></div>)}</section><section className="panel performance-panel"><div className="panel-header"><div><h2>Performance</h2><p className="panel-subtitle">Key health indicators</p></div><button className="select-button">This month <ChevronDown size={14} /></button></div><div className="performance-item"><div className="performance-label"><span>Customer satisfaction</span><strong>92.4%</strong></div><div className="progress"><span className="mint" style={{ width: '92%' }} /></div></div><div className="performance-item"><div className="performance-label"><span>Goal completion</span><strong>78.6%</strong></div><div className="progress"><span className="coral" style={{ width: '79%' }} /></div></div><div className="performance-item"><div className="performance-label"><span>Team capacity</span><strong>64.2%</strong></div><div className="progress"><span className="blue" style={{ width: '64%' }} /></div></div><div className="benchmark"><TrendingUp size={16} /><span>You're outperforming <strong>84%</strong> of similar teams</span></div></section></div>
  </div>
}
