import { ArrowDownRight, ArrowUpRight, ChevronDown, Download, MoreHorizontal, Plus, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Badge } from '../components/Badge'
import { GrowthChart, RevenueChart } from '../components/Charts'
import { Icon } from '../components/Icons'
import { getOverview } from '../services/api'

const stats = [{ label: 'Total revenue', value: '$48,294.00', change: '+12.5%', up: true, icon: 'CircleDollarSign', tone: 'coral' }, { label: 'Total customers', value: '2,842', change: '+8.2%', up: true, icon: 'UsersRound', tone: 'mint' }, { label: 'Total orders', value: '1,284', change: '+4.6%', up: true, icon: 'ShoppingBag', tone: 'blue' }, { label: 'Conversion rate', value: '4.32%', change: '-1.2%', up: false, icon: 'Percent', tone: 'purple' }]
export function Dashboard() {
  const overview = useQuery({ queryKey: ['overview'], queryFn: getOverview, retry: 1 })
  const revenueChartData = overview.data?.revenueOverTime.map((item) => ({ month: new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }), revenue: Number((item.revenue / 1000).toFixed(1)), target: 0 })) ?? []
  const growthChartData = overview.data?.customerGrowth.map((item) => ({ month: new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }), value: item.newCustomers })) ?? []
  const recentOrders = overview.data?.recentOrders ?? []
  const topProducts = overview.data?.topProducts ?? []
  const displayDate = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(new Date())
  const liveStats = overview.data ? [
    { ...stats[0], value: `$${overview.data.revenue.toLocaleString('en-US', { minimumFractionDigits: 2 })}` },
    { ...stats[1], value: overview.data.customers.toLocaleString() },
    { ...stats[2], value: overview.data.orders.toLocaleString() },
    { ...stats[3], value: overview.data.customers ? `${((overview.data.orders / overview.data.customers) * 100).toFixed(2)}%` : '0.00%' },
  ] : stats
  return <div className="page">
    <div className="page-heading"><div><p className="eyebrow">{displayDate}</p><h1>Good morning, Basel <span className="wave">👋</span></h1><p className="page-subtitle">Here’s what’s happening with your business today.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => window.print()}><Download size={16} /> Export</button><Link className="button primary" to="/products"><Plus size={16} /> Add new</Link></div></div>
    {overview.isError && <div className="form-error" role="alert">Live dashboard data is unavailable. Start the API to see current metrics.</div>}
    <div className="stats-grid">{liveStats.map((stat) => <div className="stat-card" key={stat.label}><div className="stat-top"><span className={`stat-icon ${stat.tone}`}><Icon name={stat.icon} size={17} /></span><button className="ghost-icon" aria-label={`${stat.label} options`}><MoreHorizontal size={17} /></button></div><p className="stat-label">{stat.label}</p><div className="stat-value">{overview.isLoading ? '—' : stat.value}</div><div className="stat-footer"><span className={`change ${stat.up ? 'positive' : 'negative'}`}>{stat.up ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{stat.change}</span><span className="muted-small">vs last month</span></div></div>)}</div>
    <div className="content-grid chart-grid"><section className="panel chart-panel"><div className="panel-header"><div><h2>Revenue overview</h2><p className="panel-subtitle">Daily revenue performance</p></div><div className="panel-actions"><span className="select-button">Last 30 days <ChevronDown size={14} /></span><button className="ghost-icon"><MoreHorizontal size={18} /></button></div></div><div className="chart-legend"><span><i className="legend-dot coral" /> Revenue</span><span className="chart-total">${overview.data?.revenue.toLocaleString('en-US', { maximumFractionDigits: 0 }) ?? '—'} <span className="change positive">Live</span></span></div><RevenueChart data={revenueChartData} /></section><section className="panel chart-panel"><div className="panel-header"><div><h2>Customer growth</h2><p className="panel-subtitle">New customers over time</p></div><button className="ghost-icon"><MoreHorizontal size={18} /></button></div><div className="chart-legend"><span><i className="legend-dot mint" /> New customers</span><span className="chart-total">{overview.data?.customers.toLocaleString() ?? '—'} <span className="change positive">Live</span></span></div><GrowthChart data={growthChartData} /></section></div>
    <div className="content-grid bottom-grid"><section className="panel"><div className="panel-header"><div><h2>Recent transactions</h2><p className="panel-subtitle">Your latest orders and payments</p></div><Link className="text-link" to="/orders">View all <ArrowUpRight size={14} /></Link></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{recentOrders.slice(0, 5).map((order) => <tr key={order.id}><td><div className="person"><div className="avatar avatar-pink">{order.customer?.name.slice(0, 2).toUpperCase()}</div><div><strong>{order.customer?.name}</strong><small>Order #{order.id.slice(-8).toUpperCase()}</small></div></div></td><td className="muted-cell">{new Date(order.createdAt).toLocaleDateString()}</td><td><strong>${Number(order.total).toFixed(2)}</strong></td><td><Badge status={order.status} /></td></tr>)}</tbody></table>{overview.isSuccess && recentOrders.length === 0 && <div className="empty-state"><p>No transactions yet.</p></div>}</div></section><section className="panel activity-panel"><div className="panel-header"><div><h2>Recent activity</h2><p className="panel-subtitle">Latest team updates</p></div><button className="ghost-icon"><MoreHorizontal size={18} /></button></div><div className="activity-list"><div className="activity"><div className="activity-icon coral-bg"><Icon name="CreditCard" size={15} /></div><div><p><strong>Olivia Rhye</strong> completed a payment</p><small>2 minutes ago · $1,240.00</small></div></div><div className="activity"><div className="activity-icon mint-bg"><Icon name="UserPlus" size={15} /></div><div><p><strong>New customer</strong> joined the workspace</p><small>24 minutes ago · Phoenix Baker</small></div></div><div className="activity"><div className="activity-icon blue-bg"><Icon name="FileCheck2" size={15} /></div><div><p><strong>Monthly report</strong> was generated</p><small>1 hour ago · October 2024</small></div></div><div className="activity"><div className="activity-icon purple-bg"><Icon name="MessageSquare" size={15} /></div><div><p><strong>Support ticket</strong> received a reply</p><small>3 hours ago · #TKT-2381</small></div></div></div></section></div>
    <div className="content-grid bottom-grid"><section className="panel products-panel"><div className="panel-header"><div><h2>Top products</h2><p className="panel-subtitle">Most ordered products</p></div><Link className="text-link" to="/products">View all <ArrowUpRight size={14} /></Link></div>{topProducts.slice(0, 3).map((product, index) => { const tone = ['coral', 'mint', 'blue'][index]; const maxQuantity = Math.max(...topProducts.map((item) => item.quantity), 1); const percent = `${Math.round((product.quantity / maxQuantity) * 100)}%`; return <div className="product-row" key={product.id ?? product.name}><div className={`product-icon ${tone}`}><Icon name="Package" size={17} /></div><div className="product-name"><strong>{product.name ?? 'Unnamed product'}</strong><div className="progress"><span className={tone} style={{ width: percent }} /></div></div><strong>{product.quantity} units</strong><span className="percent">{product.orders} orders</span></div>})}{overview.isSuccess && topProducts.length === 0 && <div className="empty-state"><p>No product sales yet.</p></div>}</section><section className="panel performance-panel"><div className="panel-header"><div><h2>Performance</h2><p className="panel-subtitle">Key health indicators</p></div><button className="select-button">This month <ChevronDown size={14} /></button></div><div className="performance-item"><div className="performance-label"><span>Customer satisfaction</span><strong>92.4%</strong></div><div className="progress"><span className="mint" style={{ width: '92%' }} /></div></div><div className="performance-item"><div className="performance-label"><span>Goal completion</span><strong>78.6%</strong></div><div className="progress"><span className="coral" style={{ width: '79%' }} /></div></div><div className="performance-item"><div className="performance-label"><span>Team capacity</span><strong>64.2%</strong></div><div className="progress"><span className="blue" style={{ width: '64%' }} /></div></div><div className="benchmark"><TrendingUp size={16} /><span>You're outperforming <strong>84%</strong> of similar teams</span></div></section></div>
  </div>
}
