import { useState } from 'react'
import { Bell, Check, LockKeyhole, Mail, Plus, ShieldCheck, UserRound, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../components/Badge'
import { Icon } from '../components/Icons'

export function Team() {
  const members = [['Basel Mostafa', 'basel@nexusops.io', 'Owner', 'Active', 'BM', 'avatar-pink'], ['Olivia Rhye', 'olivia@catalogue.com', 'Admin', 'Active', 'OR', 'bg-violet-100 text-violet-700'], ['Phoenix Baker', 'phoenix@qonto.io', 'Analyst', 'Active', 'PB', 'bg-sky-100 text-sky-700'], ['Demi Wilkinson', 'demi@circooles.com', 'Viewer', 'Pending', 'DW', 'bg-rose-100 text-rose-700']]
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Workspace access</p><h1>Team</h1><p className="page-subtitle">Manage your team and workspace permissions.</p></div><button className="button primary"><Plus size={16} /> Invite member</button></div><div className="team-overview"><div><UsersRound size={19} /><strong>12 members</strong><span>across 3 teams</span></div><div><ShieldCheck size={19} /><strong>100% secure</strong><span>last audit 2 days ago</span></div><div><Mail size={19} /><strong>4 pending invites</strong><span>expires in 7 days</span></div></div><section className="panel table-panel"><div className="panel-header"><div><h2>Team members</h2><p className="panel-subtitle">People with access to this workspace</p></div><button className="button secondary"><Icon name="Settings2" size={15} /> Permissions</button></div><div className="table-wrap"><table className="wide-table"><thead><tr><th>Member</th><th>Role</th><th>Status</th><th>Last active</th></tr></thead><tbody>{members.map((member) => <tr key={member[1]}><td><div className="person"><div className={`avatar ${member[5]}`}>{member[4]}</div><div><strong>{member[0]}</strong><small>{member[1]}</small></div></div></td><td>{member[2]}</td><td><Badge status={member[3]} /></td><td className="muted-cell">Today, 9:42 AM</td></tr>)}</tbody></table></div></section></div>
}

export function Notifications() {
  const [unread, setUnread] = useState([true, true, true, false])
  const notifications = [['CreditCard', 'Payment received from Olivia Rhye', 'Your payment of $1,240.00 was successfully processed.', '2 minutes ago'], ['UserPlus', 'New customer joined your workspace', 'Phoenix Baker from Qonto started a Growth trial.', '24 minutes ago'], ['FileText', 'Your monthly report is ready', 'October performance report is available to download.', '1 hour ago'], ['MessageSquare', 'Support ticket received a reply', 'Alex from support replied to ticket #TKT-2381.', '3 hours ago']] as const
  return <div className="page narrow-page"><div className="page-heading"><div><p className="eyebrow">Stay in the loop</p><h1>Notifications</h1><p className="page-subtitle">You have {unread.filter(Boolean).length} unread notifications.</p></div><button className="button secondary" onClick={() => setUnread(unread.map(() => false))}><Check size={16} /> Mark all read</button></div><section className="panel notification-list">{notifications.map(([icon, title, description, time], index) => <button className={`notification ${unread[index] ? 'unread' : ''}`} key={title} onClick={() => setUnread((current) => current.map((value, item) => item === index ? false : value))}><div className={`activity-icon ${index === 0 ? 'coral-bg' : index === 1 ? 'mint-bg' : index === 2 ? 'blue-bg' : 'purple-bg'}`}><Icon name={icon} size={16} /></div><div><strong>{title}</strong><p>{description}</p><small>{time}</small></div>{unread[index] && <span className="unread-dot" />}</button>)}</section></div>
}

export function Settings() {
  const [activeTab, setActiveTab] = useState('Account')
  const [saved, setSaved] = useState(false)
  const [productUpdates, setProductUpdates] = useState(true)
  const [weeklyDigest, setWeeklyDigest] = useState(true)
  const [securityAlerts, setSecurityAlerts] = useState(true)
  const [theme, setTheme] = useState(() => localStorage.getItem('nexusops-theme') === 'dark' ? 'Dark' : 'Light')
  const tabs = [{ label: 'Account', icon: UserRound }, { label: 'Notifications', icon: Bell }, { label: 'Security', icon: LockKeyhole }, { label: 'Appearance', icon: PaletteIcon }]
  const saveChanges = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200) }
  return <div className="page settings-page"><div className="page-heading"><div><p className="eyebrow">Workspace preferences</p><h1>Settings</h1><p className="page-subtitle">Manage your account, notifications, and workspace.</p></div>{saved && <div className="save-confirmation"><Check size={15} /> Changes saved</div>}</div><div className="settings-layout"><aside className="settings-nav">{tabs.map(({ label, icon: TabIcon }) => <button key={label} className={`settings-nav-item ${activeTab === label ? 'active' : ''}`} onClick={() => setActiveTab(label)}><TabIcon size={16} /> {label}</button>)}</aside><div className="settings-content">
    {activeTab === 'Account' && <section className="panel settings-section"><div className="settings-section-header"><div><h2>Account settings</h2><p className="panel-subtitle">Update your personal details and preferences.</p></div><button className="button primary" onClick={saveChanges}><Check size={15} /> Save changes</button></div><div className="form-grid"><label>First name<input defaultValue="Basel" /></label><label>Last name<input defaultValue="Mostafa" /></label><label className="full">Email address<input defaultValue="basel@nexusops.io" type="email" /></label><label className="full">Workspace name<input defaultValue="Acme Inc." /></label></div></section>}
    {activeTab === 'Notifications' && <section className="panel settings-section"><div className="settings-section-header"><div><h2>Notification preferences</h2><p className="panel-subtitle">Choose what you want to be notified about.</p></div><button className="button primary" onClick={saveChanges}><Check size={15} /> Save changes</button></div><ToggleRow label="Product updates" description="News, feature releases, and improvements." enabled={productUpdates} onToggle={() => setProductUpdates(!productUpdates)} /><ToggleRow label="Weekly digest" description="A summary of your workspace performance." enabled={weeklyDigest} onToggle={() => setWeeklyDigest(!weeklyDigest)} /><ToggleRow label="Security alerts" description="Important login and account activity alerts." enabled={securityAlerts} onToggle={() => setSecurityAlerts(!securityAlerts)} /></section>}
    {activeTab === 'Security' && <section className="panel settings-section"><div className="settings-section-header"><div><h2>Security</h2><p className="panel-subtitle">Keep your NexusOps account protected.</p></div></div><div className="security-item"><div className="security-icon"><LockKeyhole size={17} /></div><div><strong>Password</strong><p>Last changed 42 days ago.</p></div><button className="button secondary" onClick={saveChanges}>Change password</button></div><div className="security-item"><div className="security-icon"><ShieldCheck size={17} /></div><div><strong>Two-factor authentication</strong><p>Add an extra layer of protection to your account.</p></div><button className="button secondary" onClick={saveChanges}>Enable 2FA</button></div></section>}
    {activeTab === 'Appearance' && <section className="panel settings-section"><div className="settings-section-header"><div><h2>Appearance</h2><p className="panel-subtitle">Personalize how NexusOps looks for you.</p></div><button className="button primary" onClick={saveChanges}><Check size={15} /> Save changes</button></div><div className="appearance-options"><button className={`appearance-card ${theme === 'Light' ? 'active' : ''}`} onClick={() => { setTheme('Light'); localStorage.setItem('nexusops-theme', 'light'); window.dispatchEvent(new Event('nexusops-theme')); saveChanges() }}><div className="appearance-preview light-preview" /><strong>Light</strong><span>Clean and bright</span></button><button className={`appearance-card ${theme === 'Dark' ? 'active' : ''}`} onClick={() => { setTheme('Dark'); localStorage.setItem('nexusops-theme', 'dark'); window.dispatchEvent(new Event('nexusops-theme')); saveChanges() }}><div className="appearance-preview dark-preview" /><strong>Dark</strong><span>Easy on the eyes</span></button></div></section>}
  </div></div></div>
}

function ToggleRow({ label, description, enabled, onToggle }: { label: string; description: string; enabled: boolean; onToggle: () => void }) {
  return <div className="toggle-row"><div><strong>{label}</strong><p>{description}</p></div><button className={`toggle ${enabled ? 'on' : ''}`} aria-label={`${label} ${enabled ? 'enabled' : 'disabled'}`} aria-pressed={enabled} onClick={onToggle}><span /></button></div>
}
function PaletteIcon(props: { size: number }) { return <Icon name="Palette" {...props} /> }
export function Profile() { return <div className="page"><div className="empty-state"><UserRound size={28} /><h3>Profile</h3><p>Your profile is managed in Account settings.</p><Link to="/settings" className="button primary">Go to settings</Link></div></div> }
